//! Rust code generator.
//!
//! Converts a validated `BoeFile` into a single Rust source file that
//! depends on `boeidl::runtime::*`.

use std::collections::HashMap;
use std::fmt::Write as _;

use crate::ast::*;

/// Generate Rust source for a `.boe` file. The returned string is a complete
/// Rust module (no surrounding `mod`) and should be written to e.g.
/// `src/generated/mod130.rs`.
pub fn generate(file: &BoeFile) -> String {
    let mut out = String::new();

    emit_header(&mut out, file);
    emit_constants(&mut out, file);
    let single = file.records.len() == 1;
    for r in &file.records {
        emit_record(&mut out, &file.model, r, single);
    }

    if let Some(env) = &file.envelope {
        emit_envelope(&mut out, &file.model, env, &file.records, single);
    }

    out
}

fn struct_name(model_number: &str, record_name: &str) -> String {
    if record_name.starts_with("mod") {
        pascal_case(record_name)
    } else {
        format!("Mod{}{}", model_number, pascal_case(record_name))
    }
}

fn file_struct_name(model_number: &str) -> String {
    format!("Mod{model_number}Envelope")
}

/// Length of a param when interpolated (= its `length`, fixed width).
fn param_len(env: &Envelope, name: &str) -> usize {
    env.params
        .iter()
        .find(|p| p.name == name)
        .map(|p| p.length)
        .unwrap_or(0)
}

fn pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper = true;
    for ch in s.chars() {
        if ch == '_' || ch == '-' {
            upper = true;
        } else if upper {
            out.extend(ch.to_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn record_length_const_name(record_name: &str, single: bool) -> String {
    if single {
        "RECORD_LENGTH".to_string()
    } else {
        format!("RECORD_LENGTH_{}", upper_snake(record_name))
    }
}

fn upper_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut prev_lower = false;
    for ch in s.chars() {
        if ch == '-' {
            out.push('_');
            prev_lower = false;
        } else if ch.is_ascii_uppercase() {
            if prev_lower {
                out.push('_');
            }
            out.push(ch);
            prev_lower = false;
        } else {
            out.extend(ch.to_uppercase());
            prev_lower = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        }
    }
    out
}

// ── context ────────────────────────────────────────────────────────────

struct Context<'a> {
    record: &'a Record,
    struct_name: String,
    record_length_const: String,
    /// Map from field name → type (for expression generation).
    field_types: HashMap<&'a str, FieldType>,
}

impl<'a> Context<'a> {
    fn new(model: &Model, record: &'a Record, single: bool) -> Self {
        let struct_name = struct_name(&model.number, &record.name);
        let record_length_const = record_length_const_name(&record.name, single);
        let field_types = record
            .fields
            .iter()
            .map(|f| (f.name.as_str(), f.ty))
            .collect();
        Self {
            record,
            struct_name,
            record_length_const,
            field_types,
        }
    }

    /// Fields that appear as members of the generated struct.
    /// Fixed fields are written as constants at marshal time and are skipped.
    fn struct_fields(&self) -> impl Iterator<Item = &Field> {
        self.record.fields.iter().filter(|f| f.fixed.is_none())
    }
}

fn emit_record(out: &mut String, model: &Model, record: &Record, single: bool) {
    let ctx = Context::new(model, record, single);
    emit_record_length_const(out, record, &ctx);
    emit_struct(out, &ctx);
    emit_impl(out, record, &ctx);
}

fn emit_record_length_const(out: &mut String, record: &Record, ctx: &Context) {
    writeln!(
        out,
        "pub const {}: usize = {};",
        ctx.record_length_const, record.record_length
    )
    .unwrap();
    writeln!(out).unwrap();
}

// ── emitters ───────────────────────────────────────────────────────────

fn emit_header(out: &mut String, file: &BoeFile) {
    writeln!(out, "// Auto-generated by boeidl. Do not edit.").unwrap();
    writeln!(
        out,
        "// Model {} version {}",
        file.model.number, file.model.version
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use boeidl::runtime::*;").unwrap();
    writeln!(out).unwrap();
}

fn emit_constants(out: &mut String, file: &BoeFile) {
    writeln!(
        out,
        "pub const MODEL_NUMBER: &str = \"{}\";",
        file.model.number
    )
    .unwrap();
    writeln!(
        out,
        "pub const MODEL_VERSION: &str = \"{}\";",
        file.model.version
    )
    .unwrap();
}

fn rust_type_for(ty: FieldType) -> &'static str {
    match ty {
        FieldType::Alpha | FieldType::Alphanumeric | FieldType::Number => "String",
        FieldType::SignedAmount | FieldType::SignedAmountN | FieldType::UnsignedAmount => "i64",
    }
}

fn emit_struct(out: &mut String, ctx: &Context) {
    writeln!(out, "#[derive(Debug, Clone, Default, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub struct {} {{", ctx.struct_name).unwrap();
    for f in ctx.struct_fields() {
        if let Some(desc) = &f.description {
            writeln!(out, "    /// {}", desc).unwrap();
        }
        writeln!(out, "    pub {}: {},", f.name, rust_type_for(f.ty)).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_impl(out: &mut String, record: &Record, ctx: &Context) {
    writeln!(out, "impl {} {{", ctx.struct_name).unwrap();
    emit_marshal(out, record, ctx);
    emit_unmarshal(out, record, ctx);
    emit_compute_derived(out, record, ctx);
    emit_validate(out, record, ctx);
    writeln!(out, "}}").unwrap();
}

// ── marshal ────────────────────────────────────────────────────────────

fn emit_marshal(out: &mut String, record: &Record, ctx: &Context) {
    writeln!(
        out,
        "    pub fn marshal(&self) -> Result<Vec<u8>, AeatError> {{"
    )
    .unwrap();
    writeln!(
        out,
        "        let mut buf: Vec<u8> = vec![b' '; {}];",
        ctx.record_length_const
    )
    .unwrap();

    // Fields in declaration order
    for f in &record.fields {
        match f.fixed.as_deref() {
            Some(fixed) => {
                writeln!(
                    out,
                    "        write_field(&mut buf, {}, {}, \"{}\", \"{}\")?;",
                    f.at,
                    f.length,
                    escape_str(fixed),
                    f.name
                )
                .unwrap();
            }
            None => emit_marshal_field(out, f),
        }
    }

    // Pad numeric fields' initial space background with '0' where needed.
    // Handled by the per-field writes below (signed_amount/number both
    // emit their own padding), so the base-of-spaces is fine.

    writeln!(out, "        Ok(buf)").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
}

fn emit_marshal_field(out: &mut String, f: &Field) {
    let name = &f.name;
    match f.ty {
        FieldType::Alpha => {
            writeln!(
                out,
                "        {{ let s = pad_right(&sanitize_alpha(&self.{name}), {}, ' '); \
                 if s.chars().count() > {} {{ return Err(AeatError::FieldOverflow {{ field: \"{name}\".to_string(), width: {}, got: s.chars().count() }}); }} \
                 write_field(&mut buf, {}, {}, &s, \"{name}\")?; }}",
                f.length, f.length, f.length, f.at, f.length,
            )
            .unwrap();
        }
        FieldType::Alphanumeric => {
            writeln!(
                out,
                "        {{ let s = pad_right(&sanitize_alphanumeric(&self.{name}), {}, ' '); \
                 if s.chars().count() > {} {{ return Err(AeatError::FieldOverflow {{ field: \"{name}\".to_string(), width: {}, got: s.chars().count() }}); }} \
                 write_field(&mut buf, {}, {}, &s, \"{name}\")?; }}",
                f.length, f.length, f.length, f.at, f.length,
            )
            .unwrap();
        }
        FieldType::Number => {
            // Zero-padded left; input is a String of digits (non-digits stripped).
            writeln!(
                out,
                "        {{ let digits: String = self.{name}.chars().filter(|c| c.is_ascii_digit()).collect(); \
                 if digits.chars().count() > {} {{ return Err(AeatError::FieldOverflow {{ field: \"{name}\".to_string(), width: {}, got: digits.chars().count() }}); }} \
                 let s = pad_left(&digits, {}, '0'); \
                 write_field(&mut buf, {}, {}, &s, \"{name}\")?; }}",
                f.length, f.length, f.length, f.at, f.length,
            )
            .unwrap();
        }
        FieldType::SignedAmount => {
            let decimals = f.decimals.unwrap_or(0);
            writeln!(
                out,
                "        {{ let s = encode_signed_amount(\"{name}\", self.{name}, {}, {})?; \
                 write_field(&mut buf, {}, {}, &s, \"{name}\")?; }}",
                f.length, decimals, f.at, f.length,
            )
            .unwrap();
        }
        FieldType::SignedAmountN => {
            let decimals = f.decimals.unwrap_or(0);
            writeln!(
                out,
                "        {{ let s = encode_signed_amount_n(\"{name}\", self.{name}, {}, {})?; \
                 write_field(&mut buf, {}, {}, &s, \"{name}\")?; }}",
                f.length, decimals, f.at, f.length,
            )
            .unwrap();
        }
        FieldType::UnsignedAmount => {
            let decimals = f.decimals.unwrap_or(0);
            writeln!(
                out,
                "        {{ let s = encode_unsigned_amount(\"{name}\", self.{name}, {}, {})?; \
                 write_field(&mut buf, {}, {}, &s, \"{name}\")?; }}",
                f.length, decimals, f.at, f.length,
            )
            .unwrap();
        }
    }
}

// ── unmarshal ──────────────────────────────────────────────────────────

fn emit_unmarshal(out: &mut String, record: &Record, ctx: &Context) {
    writeln!(
        out,
        "    pub fn unmarshal(data: &[u8]) -> Result<Self, AeatError> {{"
    )
    .unwrap();
    writeln!(
        out,
        "        if data.len() < {rl} {{ return Err(AeatError::ShortRecord {{ expected: {rl}, got: data.len() }}); }}",
        rl = ctx.record_length_const
    )
    .unwrap();
    writeln!(out, "        let mut out = Self::default();").unwrap();

    for f in &record.fields {
        if let Some(fixed) = &f.fixed {
            // Fixed fields aren't struct members, but we still verify the
            // literal is present so a corrupted delimiter (e.g. `<AUX>`,
            // `<T13001000>`, the `130` model tag) fails loudly on import.
            // `at` is 1-indexed; `verify_literal` takes a 0-indexed offset.
            writeln!(
                out,
                "        verify_literal(data, {}, \"{}\", \"{}\")?;",
                f.at - 1,
                escape_str(fixed),
                f.name
            )
            .unwrap();
            continue;
        }
        let name = &f.name;
        match f.ty {
            FieldType::Alpha | FieldType::Alphanumeric => {
                writeln!(
                    out,
                    "        out.{name} = read_field(data, {}, {}).trim_end().to_string();",
                    f.at, f.length
                )
                .unwrap();
            }
            FieldType::Number => {
                writeln!(
                    out,
                    "        out.{name} = read_field(data, {}, {});",
                    f.at, f.length
                )
                .unwrap();
            }
            FieldType::SignedAmount => {
                writeln!(
                    out,
                    "        out.{name} = parse_signed_amount(data, {}, {})?;",
                    f.at, f.length
                )
                .unwrap();
            }
            FieldType::SignedAmountN => {
                writeln!(
                    out,
                    "        out.{name} = parse_signed_amount_n(data, {}, {})?;",
                    f.at, f.length
                )
                .unwrap();
            }
            FieldType::UnsignedAmount => {
                writeln!(
                    out,
                    "        out.{name} = parse_unsigned_amount(data, {}, {})?;",
                    f.at, f.length
                )
                .unwrap();
            }
        }
    }

    writeln!(out, "        Ok(out)").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
}

// ── compute_derived ────────────────────────────────────────────────────

fn emit_compute_derived(out: &mut String, record: &Record, ctx: &Context) {
    writeln!(out, "    pub fn compute_derived(&mut self) {{").unwrap();
    for d in &record.derives {
        // Fixed fields are never derived — skip if target is fixed.
        let target = record.fields.iter().find(|f| f.name == d.target);
        if target.map(|f| f.fixed.is_some()).unwrap_or(false) {
            continue;
        }
        let expr = emit_expr(&d.expr, ctx);
        writeln!(out, "        self.{} = {};", d.target, expr).unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
}

// ── validate ───────────────────────────────────────────────────────────

fn emit_validate(out: &mut String, record: &Record, ctx: &Context) {
    writeln!(out, "    pub fn validate(&self) -> Vec<AeatDiagnostic> {{").unwrap();
    writeln!(out, "        let mut diags = Vec::new();").unwrap();
    for c in &record.checks {
        let rule = emit_bool(&c.rule, ctx);
        let severity = match c.severity {
            Severity::Error => "Severity::Error",
            Severity::Warning => "Severity::Warning",
        };
        writeln!(
            out,
            "        if !({rule}) {{ diags.push(AeatDiagnostic {{ code: \"{}\".to_string(), severity: {severity}, message: \"{}\".to_string(), field: None }}); }}",
            c.code,
            escape_str(&c.message)
        )
        .unwrap();
    }
    writeln!(out, "        diags").unwrap();
    writeln!(out, "    }}").unwrap();
}

// ── expression → Rust ──────────────────────────────────────────────────

fn emit_expr(e: &Expr, ctx: &Context) -> String {
    match e {
        Expr::Int(n) => format!("{n}i64"),
        Expr::Str(s) => format!("\"{}\"", escape_str(s)),
        Expr::Ident(name) => match ctx.field_types.get(name.as_str()) {
            Some(FieldType::SignedAmount)
            | Some(FieldType::SignedAmountN)
            | Some(FieldType::UnsignedAmount) => {
                format!("self.{name}")
            }
            Some(_) => format!("self.{name}.as_str()"),
            None => format!("self.{name}"), // will be a compile error if unknown — validator catches this first
        },
        Expr::Bin(a, op, b) => {
            let op_s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
            };
            format!("({} {} {})", emit_expr(a, ctx), op_s, emit_expr(b, ctx))
        }
        Expr::Call(f, args) => {
            let name = match f {
                BuiltinFn::Max => "std::cmp::max",
                BuiltinFn::Min => "std::cmp::min",
            };
            let args_s: Vec<String> = args.iter().map(|a| emit_expr(a, ctx)).collect();
            format!("{name}({})", args_s.join(", "))
        }
    }
}

fn emit_bool(b: &BoolExpr, ctx: &Context) -> String {
    match b {
        BoolExpr::Cmp(a, op, b) => {
            let op_s = match op {
                CmpOp::Eq => "==",
                CmpOp::Ne => "!=",
                CmpOp::Gt => ">",
                CmpOp::Lt => "<",
                CmpOp::Ge => ">=",
                CmpOp::Le => "<=",
            };
            format!("({} {} {})", emit_expr(a, ctx), op_s, emit_expr(b, ctx))
        }
        BoolExpr::Implies(l, r) => {
            format!("(!({}) || ({}))", emit_bool(l, ctx), emit_bool(r, ctx))
        }
    }
}

// ── envelope ───────────────────────────────────────────────────────────

/// Total byte length of the envelope file: header + all contained records +
/// trailer. Everything is fixed-length, so this is a compile-time constant.
fn envelope_length(env: &Envelope, records: &[Record]) -> usize {
    let tmpl_len = |t: &Template| -> usize {
        t.0.iter()
            .map(|p| match p {
                TemplatePart::Lit(s) => s.chars().count(),
                TemplatePart::Field(name) => param_len(env, name),
            })
            .sum()
    };
    let body: usize = env
        .contains
        .iter()
        .map(|rec| {
            records
                .iter()
                .find(|r| r.name == *rec)
                .map(|r| r.record_length)
                .unwrap_or(0)
        })
        .sum();
    tmpl_len(&env.header) + body + tmpl_len(&env.trailer)
}

fn emit_envelope(
    out: &mut String,
    model: &Model,
    env: &Envelope,
    records: &[Record],
    single: bool,
) {
    let name = file_struct_name(&model.number);

    // ── struct ──
    writeln!(out, "#[derive(Debug, Clone, Default, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub struct {name} {{").unwrap();
    for p in &env.params {
        if let Some(d) = &p.description {
            writeln!(out, "    /// {d}").unwrap();
        }
        writeln!(out, "    pub {}: String,", p.name).unwrap();
    }
    for rec in &env.contains {
        writeln!(out, "    pub {}: {},", rec, struct_name(&model.number, rec)).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl {name} {{").unwrap();
    emit_envelope_marshal(out, env);
    emit_envelope_unmarshal(out, model, env, records, single);
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_envelope_marshal(out: &mut String, env: &Envelope) {
    writeln!(
        out,
        "    pub fn marshal(&self) -> Result<Vec<u8>, AeatError> {{"
    )
    .unwrap();
    writeln!(out, "        let mut buf: Vec<u8> = Vec::new();").unwrap();
    emit_template_marshal(out, env, &env.header);
    for rec in &env.contains {
        writeln!(
            out,
            "        buf.extend_from_slice(&self.{rec}.marshal()?);"
        )
        .unwrap();
    }
    emit_template_marshal(out, env, &env.trailer);
    writeln!(out, "        Ok(buf)").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
}

fn emit_template_marshal(out: &mut String, env: &Envelope, tmpl: &Template) {
    for part in &tmpl.0 {
        match part {
            TemplatePart::Lit(s) => {
                writeln!(
                    out,
                    "        append_latin1(&mut buf, \"{}\")?;",
                    escape_str(s)
                )
                .unwrap();
            }
            TemplatePart::Field(name) => {
                let len = param_len(env, name);
                let ty = env.params.iter().find(|p| p.name == *name).map(|p| p.ty);
                match ty {
                    Some(FieldType::Number) => {
                        writeln!(out,
                            "        {{ let digits: String = self.{name}.chars().filter(|c| c.is_ascii_digit()).collect(); \
                             if digits.chars().count() > {len} {{ return Err(AeatError::FieldOverflow {{ field: \"{name}\".to_string(), width: {len}, got: digits.chars().count() }}); }} \
                             append_latin1(&mut buf, &pad_left(&digits, {len}, '0'))?; }}").unwrap();
                    }
                    _ => {
                        // alpha / alphanumeric
                        writeln!(out,
                            "        {{ let s = pad_right(&sanitize_alphanumeric(&self.{name}), {len}, ' '); \
                             if s.chars().count() > {len} {{ return Err(AeatError::FieldOverflow {{ field: \"{name}\".to_string(), width: {len}, got: s.chars().count() }}); }} \
                             append_latin1(&mut buf, &s)?; }}").unwrap();
                    }
                }
            }
        }
    }
}

fn emit_envelope_unmarshal(
    out: &mut String,
    model: &Model,
    env: &Envelope,
    records: &[Record],
    single: bool,
) {
    let total = envelope_length(env, records);
    writeln!(
        out,
        "    pub fn unmarshal(data: &[u8]) -> Result<Self, AeatError> {{"
    )
    .unwrap();
    // Exact-length guard: rejects short buffers (which would otherwise panic in
    // the unchecked `read_field` slice) and trailing data past the envelope.
    writeln!(
        out,
        "        if data.len() != {total} {{ return Err(AeatError::WrongLength {{ expected: {total}, got: data.len() }}); }}"
    )
    .unwrap();
    writeln!(out, "        let mut out = Self::default();").unwrap();
    writeln!(out, "        let mut off = 0usize;").unwrap();
    // Header params are the source of truth (assigned); the trailer's copies
    // are verified to match so a file with divergent header/trailer fails.
    emit_template_unmarshal(out, env, &env.header, "header", true);
    for rec in &env.contains {
        let rl_const = record_length_const_name(rec, single);
        let st = struct_name(&model.number, rec);
        writeln!(out,
            "        {{ let end = off + {rl_const}; if data.len() < end {{ return Err(AeatError::ShortRecord {{ expected: end, got: data.len() }}); }} \
             out.{rec} = {st}::unmarshal(&data[off..end])?; off = end; }}").unwrap();
    }
    emit_template_unmarshal(out, env, &env.trailer, "trailer", false);
    writeln!(out, "        let _ = off;").unwrap();
    writeln!(out, "        Ok(out)").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
}

/// Emit unmarshal code for a header/trailer template. `assign` picks the mode:
/// the header assigns params into `out`; the trailer verifies its param copies
/// equal the header-derived values (and errors on mismatch). Literals are always
/// verified. `read_field` is 1-indexed; `off` is 0-indexed, hence `off + 1`.
fn emit_template_unmarshal(
    out: &mut String,
    env: &Envelope,
    tmpl: &Template,
    ctx: &str,
    assign: bool,
) {
    for part in &tmpl.0 {
        match part {
            TemplatePart::Lit(s) => {
                writeln!(
                    out,
                    "        verify_literal(data, off, \"{}\", \"{ctx}\")?; off += {};",
                    escape_str(s),
                    s.chars().count()
                )
                .unwrap();
            }
            TemplatePart::Field(name) => {
                let len = param_len(env, name);
                let ty = env.params.iter().find(|p| p.name == *name).map(|p| p.ty);
                // Number params keep their raw (zero-padded) string; text params trim.
                let read = match ty {
                    Some(FieldType::Number) => format!("read_field(data, off + 1, {len})"),
                    _ => format!("read_field(data, off + 1, {len}).trim_end().to_string()"),
                };
                if assign {
                    writeln!(out, "        out.{name} = {read}; off += {len};").unwrap();
                } else {
                    writeln!(out,
                        "        {{ let v = {read}; if v != out.{name} {{ return Err(AeatError::InvalidDelimiter {{ context: \"{ctx}\".to_string(), expected: out.{name}.clone(), got: v }}); }} off += {len}; }}").unwrap();
                }
            }
        }
    }
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
