//! Runtime support for code generated by boeidl.
//!
//! Generated modules depend on these types and helpers to marshal/unmarshal
//! AEAT fixed-position records.

pub mod bytes;
pub mod encode;
pub mod errors;
pub mod sanitize;

pub use bytes::{parse_signed_amount, read_field, write_field};
pub use encode::{encode_number, encode_signed_amount, pad_left, pad_right};
pub use errors::{AeatDiagnostic, AeatError, Severity};
pub use sanitize::{sanitize_alpha, sanitize_alphanumeric};
