use boeidl::codegen::rust::generate;
use boeidl::parse;

const MOD130: &str = include_str!("../../../models/mod130.boe");

fn gen() -> String {
    let file = parse(MOD130).expect("parse");
    generate(&file)
}

#[test]
fn header_and_constants() {
    let src = gen();
    assert!(src.contains("// Auto-generated by boeidl"));
    assert!(src.contains("use boeidl::runtime::*;"));
    assert!(src.contains("pub const MODEL_NUMBER: &str = \"130\";"));
    assert!(src.contains("pub const MODEL_VERSION: &str = \"2015-v11\";"));
    assert!(src.contains("pub const RECORD_LENGTH: usize = 878;"));
}

#[test]
fn struct_contains_non_fixed_fields() {
    let src = gen();
    assert!(src.contains("pub struct Mod130"));
    // signed_amount → i64
    assert!(src.contains("pub c01_ingresos: i64,"));
    // alphanumeric → String
    assert!(src.contains("pub nif: String,"));
    // alpha → String
    assert!(src.contains("pub nombre: String,"));
    // number → String
    assert!(src.contains("pub ejercicio: String,"));
}

#[test]
fn fixed_fields_not_in_struct() {
    let src = gen();
    // `modelo` has fixed = "130", should NOT be a struct field
    assert!(!src.contains("pub modelo: "));
    // `pagina` fixed, too
    assert!(!src.contains("pub pagina: "));
}

#[test]
fn marshal_writes_fixed_values() {
    let src = gen();
    // The fixed value "130" should appear as a literal write_field for `modelo`
    assert!(
        src.contains("write_field(&mut buf, 1, 3, \"130\", \"modelo\")"),
        "missing fixed marshal for modelo"
    );
}

#[test]
fn marshal_uses_encode_signed_amount_for_amounts() {
    let src = gen();
    assert!(
        src.contains("encode_signed_amount(\"c01_ingresos\", self.c01_ingresos, 13, 2)"),
        "missing signed_amount encode for c01_ingresos"
    );
}

#[test]
fn unmarshal_parses_fields() {
    let src = gen();
    assert!(src.contains("pub fn unmarshal(data: &[u8])"));
    assert!(src.contains("ShortRecord"));
    assert!(src.contains("parse_signed_amount(data, 77, 13)"));
    assert!(src.contains("read_field(data, 13, 9)"));
}

#[test]
fn compute_derived_emits_assignments() {
    let src = gen();
    // c03 = c01 - c02
    assert!(src.contains("self.c03_rendimiento_neto = (self.c01_ingresos - self.c02_gastos);"));
    // c04 = max(c03, 0) * 20 / 100
    assert!(src.contains("std::cmp::max(self.c03_rendimiento_neto, 0i64)"));
}

#[test]
fn validate_emits_checks() {
    let src = gen();
    assert!(src.contains("pub fn validate(&self) -> Vec<AeatDiagnostic>"));
    // E301: c03 == c01 - c02
    assert!(src.contains("\"E301\""));
    assert!(src.contains("Severity::Error"));
    // W001 has implies → !(...) || (...)
    assert!(src.contains("\"W001\""));
    assert!(src.contains("Severity::Warning"));
    // text comparison uses .as_str()
    assert!(src.contains("self.tipo_declaracion.as_str() == \"N\""));
}

#[test]
fn golden_snapshot() {
    let src = gen();
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/mod130_expected.rs"
    );
    if std::env::var("UPDATE_GOLDEN").is_ok() {
        std::fs::create_dir_all(std::path::Path::new(path).parent().unwrap()).unwrap();
        std::fs::write(path, &src).unwrap();
        return;
    }
    let expected = std::fs::read_to_string(path).unwrap_or_else(|_| {
        panic!(
            "golden file missing: {path}\nRun: UPDATE_GOLDEN=1 cargo test -p boeidl --test codegen_130"
        )
    });
    if expected != src {
        // Write a side-by-side diff file for easy inspection.
        let actual_path = format!("{path}.actual");
        std::fs::write(&actual_path, &src).ok();
        panic!(
            "generated code differs from golden.\nExpected: {path}\nActual:   {actual_path}\nRun: UPDATE_GOLDEN=1 cargo test -p boeidl --test codegen_130"
        );
    }
}
