// Auto-generated by boeidl. Do not edit.
// Model 130 version 2015-v11

use boeidl::runtime::*;

pub const MODEL_NUMBER: &str = "130";
pub const MODEL_VERSION: &str = "2015-v11";
pub const RECORD_LENGTH: usize = 878;

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Mod130 {
    /// Tipo declaración: B=a deducir, G=CCC-ingreso, I=ingreso, N=negativa, U=domiciliación.
    pub tipo_declaracion: String,
    /// Código Administración. Incluido en fichero ADMON.TXT.
    pub codigo_administracion: String,
    /// NIF del declarante. Cualquier NIF válido de persona física.
    pub nif: String,
    /// Comienzo del primer apellido en personas físicas.
    pub comienzo_apellido: String,
    /// Apellidos del declarante.
    pub apellidos: String,
    /// Nombre del declarante.
    pub nombre: String,
    /// Ejercicio fiscal (AAAA).
    pub ejercicio: String,
    /// Periodo: 1T, 2T, 3T o 4T.
    pub periodo: String,
    /// Casilla [01]: Ingresos computables del conjunto de actividades.
    pub c01_ingresos: i64,
    /// Casilla [02]: Gastos fiscalmente deducibles.
    pub c02_gastos: i64,
    /// Casilla [03]: Rendimiento neto (c01 - c02).
    pub c03_rendimiento_neto: i64,
    /// Casilla [04]: 20% de la casilla [03].
    pub c04_20pct: i64,
    /// Casilla [05]: A deducir de los trimestres anteriores.
    pub c05_deducir_anteriores: i64,
    /// Casilla [06]: A deducir retenciones e ingresos a cuenta.
    pub c06_retenciones: i64,
    /// Casilla [07]: Pago fraccionado previo del trimestre.
    pub c07_pago_fraccionado: i64,
    /// Casilla [08]: Volumen de ingresos actividades agrícolas/ganaderas/forestales.
    pub c08_ingresos_agricola: i64,
    /// Casilla [09]: 2% de la casilla [08].
    pub c09_2pct: i64,
    /// Casilla [10]: A deducir retenciones e ingresos a cuenta (agrícola).
    pub c10_retenciones_agricola: i64,
    /// Casilla [11]: Pago fraccionado previo del trimestre (agrícola).
    pub c11_pago_agricola: i64,
    /// Casilla [12]: Suma de pagos fraccionados previos del trimestre.
    pub c12_suma_pagos: i64,
    /// Casilla [13]: Minoración por aplicación deducción art. 80 bis.
    pub c13_minoracion_80bis: i64,
    /// Casilla [14]: Diferencia [12] - [13].
    pub c14_diferencia: i64,
    /// Casilla [15]: A deducir resultados negativos de trimestres anteriores.
    pub c15_negativos_anteriores: i64,
    /// Casilla [16]: Pago de préstamos para adquisición de vivienda habitual.
    pub c16_vivienda: i64,
    /// Casilla [17]: Total [14] - [15] - [16].
    pub c17_total: i64,
    /// Casilla [18]: A deducir resultado de las anteriores declaraciones.
    pub c18_anteriores_declaraciones: i64,
    /// Casilla [19]: Resultado de la declaración.
    pub c19_resultado: i64,
    /// Importe del ingreso [I].
    pub importe_ingreso: i64,
    /// Forma de pago: 0=no consta, 1=efectivo, 2=adeudo en cuenta, 3=domiciliación.
    pub forma_pago: String,
    /// Código cuenta cliente — Entidad.
    pub ccc_entidad: String,
    /// Código cuenta cliente — Sucursal.
    pub ccc_sucursal: String,
    /// Código cuenta cliente — DC.
    pub ccc_dc: String,
    /// Código cuenta cliente — Número de cuenta.
    pub ccc_cuenta: String,
    /// Declaración con resultado a deducir en los siguientes pagos fraccionados.
    pub resultado_a_deducir: String,
    /// Código electrónico de la declaración anterior (complementaria).
    pub codigo_electronico_anterior: String,
    /// Número de justificante de la declaración anterior (complementaria).
    pub justificante_anterior: String,
    /// Persona de contacto.
    pub persona_contacto: String,
    /// Teléfono de contacto.
    pub telefono: String,
    /// Observaciones.
    pub observaciones: String,
    /// Localidad de firma.
    pub firma_localidad: String,
    /// Día de firma.
    pub firma_dia: String,
    /// Mes de firma.
    pub firma_mes: String,
    /// Año de firma.
    pub firma_anio: String,
}

impl Mod130 {
    pub fn marshal(&self) -> Result<Vec<u8>, AeatError> {
        let mut buf: Vec<u8> = vec![b' '; RECORD_LENGTH];
        write_field(&mut buf, 1, 3, "130", "modelo")?;
        write_field(&mut buf, 4, 2, "01", "pagina")?;
        write_field(&mut buf, 6, 1, " ", "indicador_complementaria")?;
        { let s = pad_right(&sanitize_alpha(&self.tipo_declaracion), 1, ' '); if s.chars().count() > 1 { return Err(AeatError::FieldOverflow { field: "tipo_declaracion".to_string(), width: 1, got: s.chars().count() }); } write_field(&mut buf, 7, 1, &s, "tipo_declaracion")?; }
        { let digits: String = self.codigo_administracion.chars().filter(|c| c.is_ascii_digit()).collect(); if digits.chars().count() > 5 { return Err(AeatError::FieldOverflow { field: "codigo_administracion".to_string(), width: 5, got: digits.chars().count() }); } let s = pad_left(&digits, 5, '0'); write_field(&mut buf, 8, 5, &s, "codigo_administracion")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.nif), 9, ' '); if s.chars().count() > 9 { return Err(AeatError::FieldOverflow { field: "nif".to_string(), width: 9, got: s.chars().count() }); } write_field(&mut buf, 13, 9, &s, "nif")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.comienzo_apellido), 4, ' '); if s.chars().count() > 4 { return Err(AeatError::FieldOverflow { field: "comienzo_apellido".to_string(), width: 4, got: s.chars().count() }); } write_field(&mut buf, 22, 4, &s, "comienzo_apellido")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.apellidos), 30, ' '); if s.chars().count() > 30 { return Err(AeatError::FieldOverflow { field: "apellidos".to_string(), width: 30, got: s.chars().count() }); } write_field(&mut buf, 26, 30, &s, "apellidos")?; }
        { let s = pad_right(&sanitize_alpha(&self.nombre), 15, ' '); if s.chars().count() > 15 { return Err(AeatError::FieldOverflow { field: "nombre".to_string(), width: 15, got: s.chars().count() }); } write_field(&mut buf, 56, 15, &s, "nombre")?; }
        { let digits: String = self.ejercicio.chars().filter(|c| c.is_ascii_digit()).collect(); if digits.chars().count() > 4 { return Err(AeatError::FieldOverflow { field: "ejercicio".to_string(), width: 4, got: digits.chars().count() }); } let s = pad_left(&digits, 4, '0'); write_field(&mut buf, 71, 4, &s, "ejercicio")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.periodo), 2, ' '); if s.chars().count() > 2 { return Err(AeatError::FieldOverflow { field: "periodo".to_string(), width: 2, got: s.chars().count() }); } write_field(&mut buf, 75, 2, &s, "periodo")?; }
        { let s = encode_signed_amount("c01_ingresos", self.c01_ingresos, 13, 2)?; write_field(&mut buf, 77, 13, &s, "c01_ingresos")?; }
        { let s = encode_signed_amount("c02_gastos", self.c02_gastos, 13, 2)?; write_field(&mut buf, 90, 13, &s, "c02_gastos")?; }
        { let s = encode_signed_amount("c03_rendimiento_neto", self.c03_rendimiento_neto, 13, 2)?; write_field(&mut buf, 103, 13, &s, "c03_rendimiento_neto")?; }
        { let s = encode_signed_amount("c04_20pct", self.c04_20pct, 13, 2)?; write_field(&mut buf, 116, 13, &s, "c04_20pct")?; }
        { let s = encode_signed_amount("c05_deducir_anteriores", self.c05_deducir_anteriores, 13, 2)?; write_field(&mut buf, 129, 13, &s, "c05_deducir_anteriores")?; }
        { let s = encode_signed_amount("c06_retenciones", self.c06_retenciones, 13, 2)?; write_field(&mut buf, 142, 13, &s, "c06_retenciones")?; }
        { let s = encode_signed_amount("c07_pago_fraccionado", self.c07_pago_fraccionado, 13, 2)?; write_field(&mut buf, 155, 13, &s, "c07_pago_fraccionado")?; }
        { let s = encode_signed_amount("c08_ingresos_agricola", self.c08_ingresos_agricola, 13, 2)?; write_field(&mut buf, 168, 13, &s, "c08_ingresos_agricola")?; }
        { let s = encode_signed_amount("c09_2pct", self.c09_2pct, 13, 2)?; write_field(&mut buf, 181, 13, &s, "c09_2pct")?; }
        { let s = encode_signed_amount("c10_retenciones_agricola", self.c10_retenciones_agricola, 13, 2)?; write_field(&mut buf, 194, 13, &s, "c10_retenciones_agricola")?; }
        { let s = encode_signed_amount("c11_pago_agricola", self.c11_pago_agricola, 13, 2)?; write_field(&mut buf, 207, 13, &s, "c11_pago_agricola")?; }
        { let s = encode_signed_amount("c12_suma_pagos", self.c12_suma_pagos, 13, 2)?; write_field(&mut buf, 220, 13, &s, "c12_suma_pagos")?; }
        { let s = encode_signed_amount("c13_minoracion_80bis", self.c13_minoracion_80bis, 13, 2)?; write_field(&mut buf, 233, 13, &s, "c13_minoracion_80bis")?; }
        { let s = encode_signed_amount("c14_diferencia", self.c14_diferencia, 13, 2)?; write_field(&mut buf, 246, 13, &s, "c14_diferencia")?; }
        { let s = encode_signed_amount("c15_negativos_anteriores", self.c15_negativos_anteriores, 13, 2)?; write_field(&mut buf, 259, 13, &s, "c15_negativos_anteriores")?; }
        { let s = encode_signed_amount("c16_vivienda", self.c16_vivienda, 13, 2)?; write_field(&mut buf, 272, 13, &s, "c16_vivienda")?; }
        { let s = encode_signed_amount("c17_total", self.c17_total, 13, 2)?; write_field(&mut buf, 285, 13, &s, "c17_total")?; }
        { let s = encode_signed_amount("c18_anteriores_declaraciones", self.c18_anteriores_declaraciones, 13, 2)?; write_field(&mut buf, 298, 13, &s, "c18_anteriores_declaraciones")?; }
        { let s = encode_signed_amount("c19_resultado", self.c19_resultado, 13, 2)?; write_field(&mut buf, 311, 13, &s, "c19_resultado")?; }
        { let s = encode_signed_amount("importe_ingreso", self.importe_ingreso, 13, 2)?; write_field(&mut buf, 324, 13, &s, "importe_ingreso")?; }
        { let digits: String = self.forma_pago.chars().filter(|c| c.is_ascii_digit()).collect(); if digits.chars().count() > 1 { return Err(AeatError::FieldOverflow { field: "forma_pago".to_string(), width: 1, got: digits.chars().count() }); } let s = pad_left(&digits, 1, '0'); write_field(&mut buf, 337, 1, &s, "forma_pago")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.ccc_entidad), 4, ' '); if s.chars().count() > 4 { return Err(AeatError::FieldOverflow { field: "ccc_entidad".to_string(), width: 4, got: s.chars().count() }); } write_field(&mut buf, 338, 4, &s, "ccc_entidad")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.ccc_sucursal), 4, ' '); if s.chars().count() > 4 { return Err(AeatError::FieldOverflow { field: "ccc_sucursal".to_string(), width: 4, got: s.chars().count() }); } write_field(&mut buf, 342, 4, &s, "ccc_sucursal")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.ccc_dc), 2, ' '); if s.chars().count() > 2 { return Err(AeatError::FieldOverflow { field: "ccc_dc".to_string(), width: 2, got: s.chars().count() }); } write_field(&mut buf, 346, 2, &s, "ccc_dc")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.ccc_cuenta), 10, ' '); if s.chars().count() > 10 { return Err(AeatError::FieldOverflow { field: "ccc_cuenta".to_string(), width: 10, got: s.chars().count() }); } write_field(&mut buf, 348, 10, &s, "ccc_cuenta")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.resultado_a_deducir), 1, ' '); if s.chars().count() > 1 { return Err(AeatError::FieldOverflow { field: "resultado_a_deducir".to_string(), width: 1, got: s.chars().count() }); } write_field(&mut buf, 358, 1, &s, "resultado_a_deducir")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.codigo_electronico_anterior), 16, ' '); if s.chars().count() > 16 { return Err(AeatError::FieldOverflow { field: "codigo_electronico_anterior".to_string(), width: 16, got: s.chars().count() }); } write_field(&mut buf, 359, 16, &s, "codigo_electronico_anterior")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.justificante_anterior), 13, ' '); if s.chars().count() > 13 { return Err(AeatError::FieldOverflow { field: "justificante_anterior".to_string(), width: 13, got: s.chars().count() }); } write_field(&mut buf, 375, 13, &s, "justificante_anterior")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.persona_contacto), 100, ' '); if s.chars().count() > 100 { return Err(AeatError::FieldOverflow { field: "persona_contacto".to_string(), width: 100, got: s.chars().count() }); } write_field(&mut buf, 388, 100, &s, "persona_contacto")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.telefono), 9, ' '); if s.chars().count() > 9 { return Err(AeatError::FieldOverflow { field: "telefono".to_string(), width: 9, got: s.chars().count() }); } write_field(&mut buf, 488, 9, &s, "telefono")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.observaciones), 350, ' '); if s.chars().count() > 350 { return Err(AeatError::FieldOverflow { field: "observaciones".to_string(), width: 350, got: s.chars().count() }); } write_field(&mut buf, 497, 350, &s, "observaciones")?; }
        { let s = pad_right(&sanitize_alpha(&self.firma_localidad), 16, ' '); if s.chars().count() > 16 { return Err(AeatError::FieldOverflow { field: "firma_localidad".to_string(), width: 16, got: s.chars().count() }); } write_field(&mut buf, 847, 16, &s, "firma_localidad")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.firma_dia), 2, ' '); if s.chars().count() > 2 { return Err(AeatError::FieldOverflow { field: "firma_dia".to_string(), width: 2, got: s.chars().count() }); } write_field(&mut buf, 863, 2, &s, "firma_dia")?; }
        { let s = pad_right(&sanitize_alpha(&self.firma_mes), 10, ' '); if s.chars().count() > 10 { return Err(AeatError::FieldOverflow { field: "firma_mes".to_string(), width: 10, got: s.chars().count() }); } write_field(&mut buf, 865, 10, &s, "firma_mes")?; }
        { let s = pad_right(&sanitize_alphanumeric(&self.firma_anio), 4, ' '); if s.chars().count() > 4 { return Err(AeatError::FieldOverflow { field: "firma_anio".to_string(), width: 4, got: s.chars().count() }); } write_field(&mut buf, 875, 4, &s, "firma_anio")?; }
        Ok(buf)
    }

    pub fn unmarshal(data: &[u8]) -> Result<Self, AeatError> {
        if data.len() < RECORD_LENGTH { return Err(AeatError::ShortRecord { expected: RECORD_LENGTH, got: data.len() }); }
        let mut out = Self::default();
        verify_literal(data, 0, "130", "modelo")?;
        verify_literal(data, 3, "01", "pagina")?;
        verify_literal(data, 5, " ", "indicador_complementaria")?;
        out.tipo_declaracion = read_field(data, 7, 1).trim_end().to_string();
        out.codigo_administracion = read_field(data, 8, 5);
        out.nif = read_field(data, 13, 9).trim_end().to_string();
        out.comienzo_apellido = read_field(data, 22, 4).trim_end().to_string();
        out.apellidos = read_field(data, 26, 30).trim_end().to_string();
        out.nombre = read_field(data, 56, 15).trim_end().to_string();
        out.ejercicio = read_field(data, 71, 4);
        out.periodo = read_field(data, 75, 2).trim_end().to_string();
        out.c01_ingresos = parse_signed_amount(data, 77, 13)?;
        out.c02_gastos = parse_signed_amount(data, 90, 13)?;
        out.c03_rendimiento_neto = parse_signed_amount(data, 103, 13)?;
        out.c04_20pct = parse_signed_amount(data, 116, 13)?;
        out.c05_deducir_anteriores = parse_signed_amount(data, 129, 13)?;
        out.c06_retenciones = parse_signed_amount(data, 142, 13)?;
        out.c07_pago_fraccionado = parse_signed_amount(data, 155, 13)?;
        out.c08_ingresos_agricola = parse_signed_amount(data, 168, 13)?;
        out.c09_2pct = parse_signed_amount(data, 181, 13)?;
        out.c10_retenciones_agricola = parse_signed_amount(data, 194, 13)?;
        out.c11_pago_agricola = parse_signed_amount(data, 207, 13)?;
        out.c12_suma_pagos = parse_signed_amount(data, 220, 13)?;
        out.c13_minoracion_80bis = parse_signed_amount(data, 233, 13)?;
        out.c14_diferencia = parse_signed_amount(data, 246, 13)?;
        out.c15_negativos_anteriores = parse_signed_amount(data, 259, 13)?;
        out.c16_vivienda = parse_signed_amount(data, 272, 13)?;
        out.c17_total = parse_signed_amount(data, 285, 13)?;
        out.c18_anteriores_declaraciones = parse_signed_amount(data, 298, 13)?;
        out.c19_resultado = parse_signed_amount(data, 311, 13)?;
        out.importe_ingreso = parse_signed_amount(data, 324, 13)?;
        out.forma_pago = read_field(data, 337, 1);
        out.ccc_entidad = read_field(data, 338, 4).trim_end().to_string();
        out.ccc_sucursal = read_field(data, 342, 4).trim_end().to_string();
        out.ccc_dc = read_field(data, 346, 2).trim_end().to_string();
        out.ccc_cuenta = read_field(data, 348, 10).trim_end().to_string();
        out.resultado_a_deducir = read_field(data, 358, 1).trim_end().to_string();
        out.codigo_electronico_anterior = read_field(data, 359, 16).trim_end().to_string();
        out.justificante_anterior = read_field(data, 375, 13).trim_end().to_string();
        out.persona_contacto = read_field(data, 388, 100).trim_end().to_string();
        out.telefono = read_field(data, 488, 9).trim_end().to_string();
        out.observaciones = read_field(data, 497, 350).trim_end().to_string();
        out.firma_localidad = read_field(data, 847, 16).trim_end().to_string();
        out.firma_dia = read_field(data, 863, 2).trim_end().to_string();
        out.firma_mes = read_field(data, 865, 10).trim_end().to_string();
        out.firma_anio = read_field(data, 875, 4).trim_end().to_string();
        Ok(out)
    }

    pub fn compute_derived(&mut self) {
        self.c03_rendimiento_neto = (self.c01_ingresos - self.c02_gastos);
        self.c04_20pct = ((std::cmp::max(self.c03_rendimiento_neto, 0i64) * 20i64) / 100i64);
        self.c07_pago_fraccionado = ((self.c04_20pct - self.c05_deducir_anteriores) - self.c06_retenciones);
        self.c09_2pct = ((self.c08_ingresos_agricola * 2i64) / 100i64);
        self.c11_pago_agricola = (self.c09_2pct - self.c10_retenciones_agricola);
        self.c12_suma_pagos = (self.c07_pago_fraccionado + self.c11_pago_agricola);
        self.c14_diferencia = (self.c12_suma_pagos - self.c13_minoracion_80bis);
        self.c17_total = ((self.c14_diferencia - self.c15_negativos_anteriores) - self.c16_vivienda);
        self.c19_resultado = (self.c17_total - self.c18_anteriores_declaraciones);
    }

    pub fn validate(&self) -> Vec<AeatDiagnostic> {
        let mut diags = Vec::new();
        if !((self.c03_rendimiento_neto == (self.c01_ingresos - self.c02_gastos))) { diags.push(AeatDiagnostic { code: "E301".to_string(), severity: Severity::Error, message: "Rendimiento neto [03] debe ser [01] - [02].".to_string(), field: None }); }
        if !((self.c04_20pct == ((std::cmp::max(self.c03_rendimiento_neto, 0i64) * 20i64) / 100i64))) { diags.push(AeatDiagnostic { code: "E302".to_string(), severity: Severity::Error, message: "Casilla [04] debe ser 20% de [03] si [03] > 0.".to_string(), field: None }); }
        if !((self.c19_resultado == (self.c17_total - self.c18_anteriores_declaraciones))) { diags.push(AeatDiagnostic { code: "E303".to_string(), severity: Severity::Error, message: "Resultado [19] debe ser [17] - [18].".to_string(), field: None }); }
        if !((!((self.tipo_declaracion.as_str() == "N")) || ((self.c19_resultado <= 0i64)))) { diags.push(AeatDiagnostic { code: "W001".to_string(), severity: Severity::Warning, message: "Si la declaración es negativa, el resultado [19] debería ser <= 0.".to_string(), field: None }); }
        diags
    }
}
